# set the log level to either "ERROR", "DEBUG" or "INFO" to set the precision of error messages
log_level: "INFO"
# set this property if you would only like to execute a dry run. If you don't want to submit the final form
# set this property to "yes". If you do not want to use dry run mode, just set this property to "no".
dry_run: "no"
# set this property to target driver executable path
driver_path: "C:\\Users\\saurav\\Downloads"
# set this property to target driver type
driver_type: "chrome"
# set this property to house_of_nations current Home Page url
hon_home_url: "https://www.house-of-nations.de/"
# set this property to house_of_nations current Home Page title
hon_home_title: "Studentenapartments Berlin, g√ºnstige Zimmer Studenten Azubis Berlin, Zimmer mieten"
